apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: db
    type: local
  name: db-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/postgresql
  storageClassName: manual
