apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-ss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  serviceName: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: db-config
        image: postgres:17-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: db
        ports:
        - containerPort: 5432
          name: db
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 200m
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-volume-mount
      volumes:
      - name: db-volume-mount
        persistentVolumeClaim:
          claimName: db-pvc
