package database

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/canonical/lxd/lxd/db/query"
	"github.com/canonical/lxd/shared/api"
	"github.com/canonical/microcluster/cluster"
)

var _ = api.ServerEnvironment{}

var coreRemoteClusterObjects = cluster.RegisterStmt(`
SELECT core_remote_clusters.name, core_remote_clusters.cluster_certificate, core_remote_clusters.id, core_remote_clusters.created_at, core_remote_clusters.updated_at
  FROM core_remote_clusters
  ORDER BY core_remote_clusters.name
`)

var coreRemoteClusterObjectsByName = cluster.RegisterStmt(`
SELECT core_remote_clusters.name, core_remote_clusters.cluster_certificate, core_remote_clusters.id, core_remote_clusters.created_at, core_remote_clusters.updated_at
  FROM core_remote_clusters
  WHERE ( core_remote_clusters.name = ? )
  ORDER BY core_remote_clusters.name
`)

var coreRemoteClusterID = cluster.RegisterStmt(`
SELECT core_remote_clusters.id FROM core_remote_clusters
  WHERE core_remote_clusters.name = ?
`)

var coreRemoteClusterCreate = cluster.RegisterStmt(`
INSERT INTO core_remote_clusters (name, cluster_certificate, created_at, updated_at)
  VALUES (?, ?, ?, ?)
`)

var coreRemoteClusterDeleteByName = cluster.RegisterStmt(`
DELETE FROM core_remote_clusters WHERE name = ?
`)

var coreRemoteClusterUpdate = cluster.RegisterStmt(`
UPDATE core_remote_clusters
  SET name = ?, cluster_certificate = ?, created_at = ?, updated_at = ?
 WHERE id = ?
`)

// coreRemoteClusterColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the CoreRemoteCluster entity.
func coreRemoteClusterColumns() string {
	return "cores_remotes_clusters.name, cores_remotes_clusters.cluster_certificate, cores_remotes_clusters.id, cores_remotes_clusters.created_at, cores_remotes_clusters.updated_at"
}

// getCoreRemoteClusters can be used to run handwritten sql.Stmts to return a slice of objects.
func getCoreRemoteClusters(ctx context.Context, stmt *sql.Stmt, args ...any) ([]CoreRemoteCluster, error) {
	objects := make([]CoreRemoteCluster, 0)

	dest := func(scan func(dest ...any) error) error {
		c := CoreRemoteCluster{}
		err := scan(&c.Name, &c.ClusterCertificate, &c.ID, &c.CreatedAt, &c.UpdatedAt)
		if err != nil {
			return err
		}

		objects = append(objects, c)

		return nil
	}

	err := query.SelectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_remotes_clusters\" table: %w", err)
	}

	return objects, nil
}

// getCoreRemoteClustersRaw can be used to run handwritten query strings to return a slice of objects.
func getCoreRemoteClustersRaw(ctx context.Context, tx *sql.Tx, sql string, args ...any) ([]CoreRemoteCluster, error) {
	objects := make([]CoreRemoteCluster, 0)

	dest := func(scan func(dest ...any) error) error {
		c := CoreRemoteCluster{}
		err := scan(&c.Name, &c.ClusterCertificate, &c.ID, &c.CreatedAt, &c.UpdatedAt)
		if err != nil {
			return err
		}

		objects = append(objects, c)

		return nil
	}

	err := query.Scan(ctx, tx, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_remotes_clusters\" table: %w", err)
	}

	return objects, nil
}

// GetCoreRemoteClusters returns all available core_remote_clusters.
// generator: core_remote_cluster GetMany
func GetCoreRemoteClusters(ctx context.Context, tx *sql.Tx, filters ...CoreRemoteClusterFilter) ([]CoreRemoteCluster, error) {
	var err error

	// Result slice.
	objects := make([]CoreRemoteCluster, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = cluster.Stmt(tx, coreRemoteClusterObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"coreRemoteClusterObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.Name != nil {
			args = append(args, []any{filter.Name}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, coreRemoteClusterObjectsByName)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"coreRemoteClusterObjectsByName\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(coreRemoteClusterObjectsByName)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"coreRemoteClusterObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Name == nil {
			return nil, fmt.Errorf("Cannot filter on empty CoreRemoteClusterFilter")
		} else {
			return nil, fmt.Errorf("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getCoreRemoteClusters(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getCoreRemoteClustersRaw(ctx, tx, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_remotes_clusters\" table: %w", err)
	}

	return objects, nil
}

// GetCoreRemoteCluster returns the core_remote_cluster with the given key.
// generator: core_remote_cluster GetOne
func GetCoreRemoteCluster(ctx context.Context, tx *sql.Tx, name string) (*CoreRemoteCluster, error) {
	filter := CoreRemoteClusterFilter{}
	filter.Name = &name

	objects, err := GetCoreRemoteClusters(ctx, tx, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_remotes_clusters\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, api.StatusErrorf(http.StatusNotFound, "CoreRemoteCluster not found")
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"cores_remotes_clusters\" entry matches")
	}
}

// GetCoreRemoteClusterID return the ID of the core_remote_cluster with the given key.
// generator: core_remote_cluster ID
func GetCoreRemoteClusterID(ctx context.Context, tx *sql.Tx, name string) (int64, error) {
	stmt, err := cluster.Stmt(tx, coreRemoteClusterID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"coreRemoteClusterID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, name)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, api.StatusErrorf(http.StatusNotFound, "CoreRemoteCluster not found")
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"cores_remotes_clusters\" ID: %w", err)
	}

	return id, nil
}

// CoreRemoteClusterExists checks if a core_remote_cluster with the given key exists.
// generator: core_remote_cluster Exists
func CoreRemoteClusterExists(ctx context.Context, tx *sql.Tx, name string) (bool, error) {
	_, err := GetCoreRemoteClusterID(ctx, tx, name)
	if err != nil {
		if api.StatusErrorCheck(err, http.StatusNotFound) {
			return false, nil
		}

		return false, err
	}

	return true, nil
}

// CreateCoreRemoteCluster adds a new core_remote_cluster to the database.
// generator: core_remote_cluster Create
func CreateCoreRemoteCluster(ctx context.Context, tx *sql.Tx, object CoreRemoteCluster) (int64, error) {
	// Check if a core_remote_cluster with the same key exists.
	exists, err := CoreRemoteClusterExists(ctx, tx, object.Name)
	if err != nil {
		return -1, fmt.Errorf("Failed to check for duplicates: %w", err)
	}

	if exists {
		return -1, api.StatusErrorf(http.StatusConflict, "This \"cores_remotes_clusters\" entry already exists")
	}

	args := make([]any, 4)

	// Populate the statement arguments.
	args[0] = object.Name
	args[1] = object.ClusterCertificate
	args[2] = object.CreatedAt
	args[3] = object.UpdatedAt

	// Prepared statement to use.
	stmt, err := cluster.Stmt(tx, coreRemoteClusterCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"coreRemoteClusterCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil {
		return -1, fmt.Errorf("Failed to create \"cores_remotes_clusters\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"cores_remotes_clusters\" entry ID: %w", err)
	}

	return id, nil
}

// DeleteCoreRemoteCluster deletes the core_remote_cluster matching the given key parameters.
// generator: core_remote_cluster DeleteOne-by-Name
func DeleteCoreRemoteCluster(ctx context.Context, tx *sql.Tx, name string) error {
	stmt, err := cluster.Stmt(tx, coreRemoteClusterDeleteByName)
	if err != nil {
		return fmt.Errorf("Failed to get \"coreRemoteClusterDeleteByName\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(name)
	if err != nil {
		return fmt.Errorf("Delete \"cores_remotes_clusters\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return api.StatusErrorf(http.StatusNotFound, "CoreRemoteCluster not found")
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d CoreRemoteCluster rows instead of 1", n)
	}

	return nil
}

// UpdateCoreRemoteCluster updates the core_remote_cluster matching the given key parameters.
// generator: core_remote_cluster Update
func UpdateCoreRemoteCluster(ctx context.Context, tx *sql.Tx, name string, object CoreRemoteCluster) error {
	id, err := GetCoreRemoteClusterID(ctx, tx, name)
	if err != nil {
		return err
	}

	stmt, err := cluster.Stmt(tx, coreRemoteClusterUpdate)
	if err != nil {
		return fmt.Errorf("Failed to get \"coreRemoteClusterUpdate\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(object.Name, object.ClusterCertificate, object.CreatedAt, object.UpdatedAt, id)
	if err != nil {
		return fmt.Errorf("Update \"cores_remotes_clusters\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}
