package database

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/canonical/lxd/lxd/db/query"
	"github.com/canonical/lxd/shared/api"
	"github.com/canonical/microcluster/cluster"
)

var _ = api.ServerEnvironment{}

var coreSiteObjects = cluster.RegisterStmt(`
SELECT core_sites.name, core_sites.site_certificate, core_sites.id, core_sites.created_at, core_sites.updated_at
  FROM core_sites
  ORDER BY core_sites.name
`)

var coreSiteObjectsByName = cluster.RegisterStmt(`
SELECT core_sites.name, core_sites.site_certificate, core_sites.id, core_sites.created_at, core_sites.updated_at
  FROM core_sites
  WHERE ( core_sites.name = ? )
  ORDER BY core_sites.name
`)

var coreSiteID = cluster.RegisterStmt(`
SELECT core_sites.id FROM core_sites
  WHERE core_sites.name = ?
`)

var coreSiteCreate = cluster.RegisterStmt(`
INSERT INTO core_sites (name, site_certificate, created_at, updated_at)
  VALUES (?, ?, ?, ?)
`)

var coreSiteDeleteByName = cluster.RegisterStmt(`
DELETE FROM core_sites WHERE name = ?
`)

var coreSiteUpdate = cluster.RegisterStmt(`
UPDATE core_sites
  SET name = ?, site_certificate = ?, created_at = ?, updated_at = ?
 WHERE id = ?
`)

// coreSiteColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the CoreSite entity.
func coreSiteColumns() string {
	return "cores_sites.name, cores_sites.site_certificate, cores_sites.id, cores_sites.created_at, cores_sites.updated_at"
}

// getCoreSites can be used to run handwritten sql.Stmts to return a slice of objects.
func getCoreSites(ctx context.Context, stmt *sql.Stmt, args ...any) ([]CoreSite, error) {
	objects := make([]CoreSite, 0)

	dest := func(scan func(dest ...any) error) error {
		c := CoreSite{}
		err := scan(&c.Name, &c.SiteCertificate, &c.ID, &c.CreatedAt, &c.UpdatedAt)
		if err != nil {
			return err
		}

		objects = append(objects, c)

		return nil
	}

	err := query.SelectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_sites\" table: %w", err)
	}

	return objects, nil
}

// getCoreSitesRaw can be used to run handwritten query strings to return a slice of objects.
func getCoreSitesRaw(ctx context.Context, tx *sql.Tx, sql string, args ...any) ([]CoreSite, error) {
	objects := make([]CoreSite, 0)

	dest := func(scan func(dest ...any) error) error {
		c := CoreSite{}
		err := scan(&c.Name, &c.SiteCertificate, &c.ID, &c.CreatedAt, &c.UpdatedAt)
		if err != nil {
			return err
		}

		objects = append(objects, c)

		return nil
	}

	err := query.Scan(ctx, tx, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_sites\" table: %w", err)
	}

	return objects, nil
}

// GetCoreSites returns all available core_sites.
// generator: core_site GetMany
func GetCoreSites(ctx context.Context, tx *sql.Tx, filters ...CoreSiteFilter) ([]CoreSite, error) {
	var err error

	// Result slice.
	objects := make([]CoreSite, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = cluster.Stmt(tx, coreSiteObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"coreSiteObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.Name != nil {
			args = append(args, []any{filter.Name}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, coreSiteObjectsByName)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"coreSiteObjectsByName\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(coreSiteObjectsByName)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"coreSiteObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Name == nil {
			return nil, fmt.Errorf("Cannot filter on empty CoreSiteFilter")
		} else {
			return nil, fmt.Errorf("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getCoreSites(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getCoreSitesRaw(ctx, tx, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_sites\" table: %w", err)
	}

	return objects, nil
}

// GetCoreSite returns the core_site with the given key.
// generator: core_site GetOne
func GetCoreSite(ctx context.Context, tx *sql.Tx, name string) (*CoreSite, error) {
	filter := CoreSiteFilter{}
	filter.Name = &name

	objects, err := GetCoreSites(ctx, tx, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_sites\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, api.StatusErrorf(http.StatusNotFound, "CoreSite not found")
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"cores_sites\" entry matches")
	}
}

// GetCoreSiteID return the ID of the core_site with the given key.
// generator: core_site ID
func GetCoreSiteID(ctx context.Context, tx *sql.Tx, name string) (int64, error) {
	stmt, err := cluster.Stmt(tx, coreSiteID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"coreSiteID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, name)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, api.StatusErrorf(http.StatusNotFound, "CoreSite not found")
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"cores_sites\" ID: %w", err)
	}

	return id, nil
}

// CoreSiteExists checks if a core_site with the given key exists.
// generator: core_site Exists
func CoreSiteExists(ctx context.Context, tx *sql.Tx, name string) (bool, error) {
	_, err := GetCoreSiteID(ctx, tx, name)
	if err != nil {
		if api.StatusErrorCheck(err, http.StatusNotFound) {
			return false, nil
		}

		return false, err
	}

	return true, nil
}

// CreateCoreSite adds a new core_site to the database.
// generator: core_site Create
func CreateCoreSite(ctx context.Context, tx *sql.Tx, object CoreSite) (int64, error) {
	// Check if a core_site with the same key exists.
	exists, err := CoreSiteExists(ctx, tx, object.Name)
	if err != nil {
		return -1, fmt.Errorf("Failed to check for duplicates: %w", err)
	}

	if exists {
		return -1, api.StatusErrorf(http.StatusConflict, "This \"cores_sites\" entry already exists")
	}

	args := make([]any, 4)

	// Populate the statement arguments.
	args[0] = object.Name
	args[1] = object.SiteCertificate
	args[2] = object.CreatedAt
	args[3] = object.UpdatedAt

	// Prepared statement to use.
	stmt, err := cluster.Stmt(tx, coreSiteCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"coreSiteCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil {
		return -1, fmt.Errorf("Failed to create \"cores_sites\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"cores_sites\" entry ID: %w", err)
	}

	return id, nil
}

// DeleteCoreSite deletes the core_site matching the given key parameters.
// generator: core_site DeleteOne-by-Name
func DeleteCoreSite(ctx context.Context, tx *sql.Tx, name string) error {
	stmt, err := cluster.Stmt(tx, coreSiteDeleteByName)
	if err != nil {
		return fmt.Errorf("Failed to get \"coreSiteDeleteByName\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(name)
	if err != nil {
		return fmt.Errorf("Delete \"cores_sites\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return api.StatusErrorf(http.StatusNotFound, "CoreSite not found")
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d CoreSite rows instead of 1", n)
	}

	return nil
}

// UpdateCoreSite updates the core_site matching the given key parameters.
// generator: core_site Update
func UpdateCoreSite(ctx context.Context, tx *sql.Tx, name string, object CoreSite) error {
	id, err := GetCoreSiteID(ctx, tx, name)
	if err != nil {
		return err
	}

	stmt, err := cluster.Stmt(tx, coreSiteUpdate)
	if err != nil {
		return fmt.Errorf("Failed to get \"coreSiteUpdate\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(object.Name, object.SiteCertificate, object.CreatedAt, object.UpdatedAt, id)
	if err != nil {
		return fmt.Errorf("Update \"cores_sites\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}
