package database

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/canonical/lxd/lxd/db/query"
	"github.com/canonical/lxd/shared/api"
	"github.com/canonical/microcluster/cluster"
)

var _ = api.ServerEnvironment{}

var coreRemoteClusterTokenObjects = cluster.RegisterStmt(`
SELECT core_remote_cluster_tokens.cluster_name, core_remote_cluster_tokens.id, core_remote_cluster_tokens.secret, core_remote_cluster_tokens.expiry, core_remote_cluster_tokens.created_at
  FROM core_remote_cluster_tokens
  ORDER BY core_remote_cluster_tokens.cluster_name
`)

var coreRemoteClusterTokenObjectsByClusterName = cluster.RegisterStmt(`
SELECT core_remote_cluster_tokens.cluster_name, core_remote_cluster_tokens.id, core_remote_cluster_tokens.secret, core_remote_cluster_tokens.expiry, core_remote_cluster_tokens.created_at
  FROM core_remote_cluster_tokens
  WHERE ( core_remote_cluster_tokens.cluster_name = ? )
  ORDER BY core_remote_cluster_tokens.cluster_name
`)

var coreRemoteClusterTokenID = cluster.RegisterStmt(`
SELECT core_remote_cluster_tokens.id FROM core_remote_cluster_tokens
  WHERE core_remote_cluster_tokens.cluster_name = ?
`)

var coreRemoteClusterTokenCreate = cluster.RegisterStmt(`
INSERT INTO core_remote_cluster_tokens (cluster_name, secret, expiry, created_at)
  VALUES (?, ?, ?, ?)
`)

var coreRemoteClusterTokenDeleteByClusterName = cluster.RegisterStmt(`
DELETE FROM core_remote_cluster_tokens WHERE cluster_name = ?
`)

var coreRemoteClusterTokenUpdate = cluster.RegisterStmt(`
UPDATE core_remote_cluster_tokens
  SET cluster_name = ?, secret = ?, expiry = ?, created_at = ?
 WHERE id = ?
`)

// coreRemoteClusterTokenColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the CoreRemoteClusterToken entity.
func coreRemoteClusterTokenColumns() string {
	return "cores_remotes_clusters_tokens.cluster_name, cores_remotes_clusters_tokens.id, cores_remotes_clusters_tokens.secret, cores_remotes_clusters_tokens.expiry, cores_remotes_clusters_tokens.created_at"
}

// getCoreRemoteClusterTokens can be used to run handwritten sql.Stmts to return a slice of objects.
func getCoreRemoteClusterTokens(ctx context.Context, stmt *sql.Stmt, args ...any) ([]CoreRemoteClusterToken, error) {
	objects := make([]CoreRemoteClusterToken, 0)

	dest := func(scan func(dest ...any) error) error {
		c := CoreRemoteClusterToken{}
		err := scan(&c.ClusterName, &c.ID, &c.Secret, &c.Expiry, &c.CreatedAt)
		if err != nil {
			return err
		}

		objects = append(objects, c)

		return nil
	}

	err := query.SelectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_remotes_clusters_tokens\" table: %w", err)
	}

	return objects, nil
}

// getCoreRemoteClusterTokensRaw can be used to run handwritten query strings to return a slice of objects.
func getCoreRemoteClusterTokensRaw(ctx context.Context, tx *sql.Tx, sql string, args ...any) ([]CoreRemoteClusterToken, error) {
	objects := make([]CoreRemoteClusterToken, 0)

	dest := func(scan func(dest ...any) error) error {
		c := CoreRemoteClusterToken{}
		err := scan(&c.ClusterName, &c.ID, &c.Secret, &c.Expiry, &c.CreatedAt)
		if err != nil {
			return err
		}

		objects = append(objects, c)

		return nil
	}

	err := query.Scan(ctx, tx, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_remotes_clusters_tokens\" table: %w", err)
	}

	return objects, nil
}

// GetCoreRemoteClusterTokens returns all available core_remote_cluster_tokens.
// generator: core_remote_cluster_token GetMany
func GetCoreRemoteClusterTokens(ctx context.Context, tx *sql.Tx, filters ...CoreRemoteClusterTokenFilter) ([]CoreRemoteClusterToken, error) {
	var err error

	// Result slice.
	objects := make([]CoreRemoteClusterToken, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = cluster.Stmt(tx, coreRemoteClusterTokenObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"coreRemoteClusterTokenObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.ClusterName != nil {
			args = append(args, []any{filter.ClusterName}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, coreRemoteClusterTokenObjectsByClusterName)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"coreRemoteClusterTokenObjectsByClusterName\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(coreRemoteClusterTokenObjectsByClusterName)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"coreRemoteClusterTokenObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.ClusterName == nil {
			return nil, fmt.Errorf("Cannot filter on empty CoreRemoteClusterTokenFilter")
		} else {
			return nil, fmt.Errorf("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getCoreRemoteClusterTokens(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getCoreRemoteClusterTokensRaw(ctx, tx, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_remotes_clusters_tokens\" table: %w", err)
	}

	return objects, nil
}

// GetCoreRemoteClusterToken returns the core_remote_cluster_token with the given key.
// generator: core_remote_cluster_token GetOne
func GetCoreRemoteClusterToken(ctx context.Context, tx *sql.Tx, clusterName string) (*CoreRemoteClusterToken, error) {
	filter := CoreRemoteClusterTokenFilter{}
	filter.ClusterName = &clusterName

	objects, err := GetCoreRemoteClusterTokens(ctx, tx, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cores_remotes_clusters_tokens\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, api.StatusErrorf(http.StatusNotFound, "CoreRemoteClusterToken not found")
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"cores_remotes_clusters_tokens\" entry matches")
	}
}

// GetCoreRemoteClusterTokenID return the ID of the core_remote_cluster_token with the given key.
// generator: core_remote_cluster_token ID
func GetCoreRemoteClusterTokenID(ctx context.Context, tx *sql.Tx, clusterName string) (int64, error) {
	stmt, err := cluster.Stmt(tx, coreRemoteClusterTokenID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"coreRemoteClusterTokenID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, clusterName)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, api.StatusErrorf(http.StatusNotFound, "CoreRemoteClusterToken not found")
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"cores_remotes_clusters_tokens\" ID: %w", err)
	}

	return id, nil
}

// CoreRemoteClusterTokenExists checks if a core_remote_cluster_token with the given key exists.
// generator: core_remote_cluster_token Exists
func CoreRemoteClusterTokenExists(ctx context.Context, tx *sql.Tx, clusterName string) (bool, error) {
	_, err := GetCoreRemoteClusterTokenID(ctx, tx, clusterName)
	if err != nil {
		if api.StatusErrorCheck(err, http.StatusNotFound) {
			return false, nil
		}

		return false, err
	}

	return true, nil
}

// CreateCoreRemoteClusterToken adds a new core_remote_cluster_token to the database.
// generator: core_remote_cluster_token Create
func CreateCoreRemoteClusterToken(ctx context.Context, tx *sql.Tx, object CoreRemoteClusterToken) (int64, error) {
	// Check if a core_remote_cluster_token with the same key exists.
	exists, err := CoreRemoteClusterTokenExists(ctx, tx, object.ClusterName)
	if err != nil {
		return -1, fmt.Errorf("Failed to check for duplicates: %w", err)
	}

	if exists {
		return -1, api.StatusErrorf(http.StatusConflict, "This \"cores_remotes_clusters_tokens\" entry already exists")
	}

	args := make([]any, 4)

	// Populate the statement arguments.
	args[0] = object.ClusterName
	args[1] = object.Secret
	args[2] = object.Expiry
	args[3] = object.CreatedAt

	// Prepared statement to use.
	stmt, err := cluster.Stmt(tx, coreRemoteClusterTokenCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"coreRemoteClusterTokenCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil {
		return -1, fmt.Errorf("Failed to create \"cores_remotes_clusters_tokens\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"cores_remotes_clusters_tokens\" entry ID: %w", err)
	}

	return id, nil
}

// DeleteCoreRemoteClusterToken deletes the core_remote_cluster_token matching the given key parameters.
// generator: core_remote_cluster_token DeleteOne-by-ClusterName
func DeleteCoreRemoteClusterToken(ctx context.Context, tx *sql.Tx, clusterName string) error {
	stmt, err := cluster.Stmt(tx, coreRemoteClusterTokenDeleteByClusterName)
	if err != nil {
		return fmt.Errorf("Failed to get \"coreRemoteClusterTokenDeleteByClusterName\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(clusterName)
	if err != nil {
		return fmt.Errorf("Delete \"cores_remotes_clusters_tokens\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return api.StatusErrorf(http.StatusNotFound, "CoreRemoteClusterToken not found")
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d CoreRemoteClusterToken rows instead of 1", n)
	}

	return nil
}

// UpdateCoreRemoteClusterToken updates the core_remote_cluster_token matching the given key parameters.
// generator: core_remote_cluster_token Update
func UpdateCoreRemoteClusterToken(ctx context.Context, tx *sql.Tx, clusterName string, object CoreRemoteClusterToken) error {
	id, err := GetCoreRemoteClusterTokenID(ctx, tx, clusterName)
	if err != nil {
		return err
	}

	stmt, err := cluster.Stmt(tx, coreRemoteClusterTokenUpdate)
	if err != nil {
		return fmt.Errorf("Failed to get \"coreRemoteClusterTokenUpdate\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(object.ClusterName, object.Secret, object.Expiry, object.CreatedAt, id)
	if err != nil {
		return fmt.Errorf("Update \"cores_remotes_clusters_tokens\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}
