package database

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/canonical/lxd/lxd/db/query"
	"github.com/canonical/lxd/shared/api"
	"github.com/canonical/microcluster/cluster"
)

var _ = api.ServerEnvironment{}

var remoteClusterDetailObjects = cluster.RegisterStmt(`
SELECT remote_cluster_details.core_remote_cluster_id, remote_cluster_details.status, remote_cluster_details.id, remote_cluster_details.cpu_total_count, remote_cluster_details.cpu_load_1, remote_cluster_details.cpu_load_5, remote_cluster_details.cpu_load_15, remote_cluster_details.memory_total_amount, remote_cluster_details.memory_usage, remote_cluster_details.disk_total_size, remote_cluster_details.disk_usage, remote_cluster_details.instance_count, remote_cluster_details.instance_statuses, remote_cluster_details.member_count, remote_cluster_details.member_statuses, remote_cluster_details.joined_at, remote_cluster_details.updated_at
  FROM remote_cluster_details
  ORDER BY remote_cluster_details.core_remote_cluster_id
`)

var remoteClusterDetailObjectsByCoreRemoteClusterID = cluster.RegisterStmt(`
SELECT remote_cluster_details.core_remote_cluster_id, remote_cluster_details.status, remote_cluster_details.id, remote_cluster_details.cpu_total_count, remote_cluster_details.cpu_load_1, remote_cluster_details.cpu_load_5, remote_cluster_details.cpu_load_15, remote_cluster_details.memory_total_amount, remote_cluster_details.memory_usage, remote_cluster_details.disk_total_size, remote_cluster_details.disk_usage, remote_cluster_details.instance_count, remote_cluster_details.instance_statuses, remote_cluster_details.member_count, remote_cluster_details.member_statuses, remote_cluster_details.joined_at, remote_cluster_details.updated_at
  FROM remote_cluster_details
  WHERE ( remote_cluster_details.core_remote_cluster_id = ? )
  ORDER BY remote_cluster_details.core_remote_cluster_id
`)

var remoteClusterDetailID = cluster.RegisterStmt(`
SELECT remote_cluster_details.id FROM remote_cluster_details
  WHERE remote_cluster_details.core_remote_cluster_id = ?
`)

var remoteClusterDetailCreate = cluster.RegisterStmt(`
INSERT INTO remote_cluster_details (core_remote_cluster_id, status, cpu_total_count, cpu_load_1, cpu_load_5, cpu_load_15, memory_total_amount, memory_usage, disk_total_size, disk_usage, instance_count, instance_statuses, member_count, member_statuses, joined_at, updated_at)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`)

var remoteClusterDetailUpdate = cluster.RegisterStmt(`
UPDATE remote_cluster_details
  SET core_remote_cluster_id = ?, status = ?, cpu_total_count = ?, cpu_load_1 = ?, cpu_load_5 = ?, cpu_load_15 = ?, memory_total_amount = ?, memory_usage = ?, disk_total_size = ?, disk_usage = ?, instance_count = ?, instance_statuses = ?, member_count = ?, member_statuses = ?, joined_at = ?, updated_at = ?
 WHERE id = ?
`)

// remoteClusterDetailColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the RemoteClusterDetail entity.
func remoteClusterDetailColumns() string {
	return "remotes_clusters_details.core_remote_cluster_id, remotes_clusters_details.status, remotes_clusters_details.id, remotes_clusters_details.cpu_total_count, remote_cluster_details.cpu_load_1, remote_cluster_details.cpu_load_5, remote_cluster_details.cpu_load_15, remotes_clusters_details.memory_total_amount, remotes_clusters_details.memory_usage, remotes_clusters_details.disk_total_size, remotes_clusters_details.disk_usage, remotes_clusters_details.instance_count, remotes_clusters_details.instance_statuses, remotes_clusters_details.member_count, remotes_clusters_details.member_statuses, remotes_clusters_details.joined_at, remotes_clusters_details.updated_at"
}

// getRemoteClusterDetails can be used to run handwritten sql.Stmts to return a slice of objects.
func getRemoteClusterDetails(ctx context.Context, stmt *sql.Stmt, args ...any) ([]RemoteClusterDetail, error) {
	objects := make([]RemoteClusterDetail, 0)

	dest := func(scan func(dest ...any) error) error {
		r := RemoteClusterDetail{}
		err := scan(&r.CoreRemoteClusterID, &r.Status, &r.ID, &r.CPUTotalCount, &r.CPULoad1, &r.CPULoad5, &r.CPULoad15, &r.MemoryTotalAmount, &r.MemoryUsage, &r.DiskTotalSize, &r.DiskUsage, &r.InstanceCount, &r.InstanceStatuses, &r.MemberCount, &r.MemberStatuses, &r.JoinedAt, &r.UpdatedAt)
		if err != nil {
			return err
		}

		objects = append(objects, r)

		return nil
	}

	err := query.SelectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"remotes_clusters_details\" table: %w", err)
	}

	return objects, nil
}

// getRemoteClusterDetailsRaw can be used to run handwritten query strings to return a slice of objects.
func getRemoteClusterDetailsRaw(ctx context.Context, tx *sql.Tx, sql string, args ...any) ([]RemoteClusterDetail, error) {
	objects := make([]RemoteClusterDetail, 0)

	dest := func(scan func(dest ...any) error) error {
		r := RemoteClusterDetail{}
		err := scan(&r.CoreRemoteClusterID, &r.Status, &r.ID, &r.CPUTotalCount, &r.CPULoad1, &r.CPULoad5, &r.CPULoad15, &r.MemoryTotalAmount, &r.MemoryUsage, &r.DiskTotalSize, &r.DiskUsage, &r.InstanceCount, &r.InstanceStatuses, &r.MemberCount, &r.MemberStatuses, &r.JoinedAt, &r.UpdatedAt)
		if err != nil {
			return err
		}

		objects = append(objects, r)

		return nil
	}

	err := query.Scan(ctx, tx, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"remotes_clusters_details\" table: %w", err)
	}

	return objects, nil
}

// GetRemoteClusterDetails returns all available remote_cluster_details.
// generator: remote_cluster_detail GetMany
func GetRemoteClusterDetails(ctx context.Context, tx *sql.Tx, filters ...RemoteClusterDetailFilter) ([]RemoteClusterDetail, error) {
	var err error

	// Result slice.
	objects := make([]RemoteClusterDetail, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = cluster.Stmt(tx, remoteClusterDetailObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"remoteClusterDetailObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.CoreRemoteClusterID != nil {
			args = append(args, []any{filter.CoreRemoteClusterID}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, remoteClusterDetailObjectsByCoreRemoteClusterID)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"remoteClusterDetailObjectsByCoreRemoteClusterID\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(remoteClusterDetailObjectsByCoreRemoteClusterID)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"remoteClusterDetailObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.CoreRemoteClusterID == nil {
			return nil, fmt.Errorf("Cannot filter on empty RemoteClusterDetailFilter")
		} else {
			return nil, fmt.Errorf("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getRemoteClusterDetails(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getRemoteClusterDetailsRaw(ctx, tx, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"remotes_clusters_details\" table: %w", err)
	}

	return objects, nil
}

// GetRemoteClusterDetail returns the remote_cluster_detail with the given key.
// generator: remote_cluster_detail GetOne
func GetRemoteClusterDetail(ctx context.Context, tx *sql.Tx, coreRemoteClusterID int64) (*RemoteClusterDetail, error) {
	filter := RemoteClusterDetailFilter{}
	filter.CoreRemoteClusterID = &coreRemoteClusterID

	objects, err := GetRemoteClusterDetails(ctx, tx, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"remotes_clusters_details\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, api.StatusErrorf(http.StatusNotFound, "RemoteClusterDetail not found")
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"remotes_clusters_details\" entry matches")
	}
}

// GetRemoteClusterDetailID return the ID of the remote_cluster_detail with the given key.
// generator: remote_cluster_detail ID
func GetRemoteClusterDetailID(ctx context.Context, tx *sql.Tx, coreRemoteClusterID int64) (int64, error) {
	stmt, err := cluster.Stmt(tx, remoteClusterDetailID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"remoteClusterDetailID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, coreRemoteClusterID)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, api.StatusErrorf(http.StatusNotFound, "RemoteClusterDetail not found")
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"remotes_clusters_details\" ID: %w", err)
	}

	return id, nil
}

// RemoteClusterDetailExists checks if a remote_cluster_detail with the given key exists.
// generator: remote_cluster_detail Exists
func RemoteClusterDetailExists(ctx context.Context, tx *sql.Tx, coreRemoteClusterID int64) (bool, error) {
	_, err := GetRemoteClusterDetailID(ctx, tx, coreRemoteClusterID)
	if err != nil {
		if api.StatusErrorCheck(err, http.StatusNotFound) {
			return false, nil
		}

		return false, err
	}

	return true, nil
}

// CreateRemoteClusterDetail adds a new remote_cluster_detail to the database.
// generator: remote_cluster_detail Create
func CreateRemoteClusterDetail(ctx context.Context, tx *sql.Tx, object RemoteClusterDetail) (int64, error) {
	// Check if a remote_cluster_detail with the same key exists.
	exists, err := RemoteClusterDetailExists(ctx, tx, object.CoreRemoteClusterID)
	if err != nil {
		return -1, fmt.Errorf("Failed to check for duplicates: %w", err)
	}

	if exists {
		return -1, api.StatusErrorf(http.StatusConflict, "This \"remotes_clusters_details\" entry already exists")
	}

	args := make([]any, 16)

	// Populate the statement arguments.
	args[0] = object.CoreRemoteClusterID
	args[1] = object.Status
	args[2] = object.CPUTotalCount
	args[3] = object.CPULoad1
	args[4] = object.CPULoad5
	args[5] = object.CPULoad15
	args[6] = object.MemoryTotalAmount
	args[7] = object.MemoryUsage
	args[8] = object.DiskTotalSize
	args[9] = object.DiskUsage
	args[10] = object.InstanceCount
	args[11] = object.InstanceStatuses
	args[12] = object.MemberCount
	args[13] = object.MemberStatuses
	args[14] = object.JoinedAt
	args[15] = object.UpdatedAt

	// Prepared statement to use.
	stmt, err := cluster.Stmt(tx, remoteClusterDetailCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"remoteClusterDetailCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil {
		return -1, fmt.Errorf("Failed to create \"remotes_clusters_details\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"remotes_clusters_details\" entry ID: %w", err)
	}

	return id, nil
}

// UpdateRemoteClusterDetail updates the remote_cluster_detail matching the given key parameters.
// generator: remote_cluster_detail Update
func UpdateRemoteClusterDetail(ctx context.Context, tx *sql.Tx, coreRemoteClusterID int64, object RemoteClusterDetail) error {
	id, err := GetRemoteClusterDetailID(ctx, tx, coreRemoteClusterID)
	if err != nil {
		return err
	}

	stmt, err := cluster.Stmt(tx, remoteClusterDetailUpdate)
	if err != nil {
		return fmt.Errorf("Failed to get \"remoteClusterDetailUpdate\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(object.CoreRemoteClusterID, object.Status, object.CPUTotalCount, object.CPULoad1, object.CPULoad5, object.CPULoad15, object.MemoryTotalAmount, object.MemoryUsage, object.DiskTotalSize, object.DiskUsage, object.InstanceCount, object.InstanceStatuses, object.MemberCount, object.MemberStatuses, object.JoinedAt, object.UpdatedAt, id)
	if err != nil {
		return fmt.Errorf("Update \"remotes_clusters_details\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}
