package database

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/canonical/lxd/lxd/db/query"
	"github.com/canonical/lxd/shared/api"
	"github.com/canonical/microcluster/cluster"
)

var _ = api.ServerEnvironment{}

var siteDetailObjects = cluster.RegisterStmt(`
SELECT site_details.core_site_id, site_details.status, site_details.id, site_details.cpu_total_count, site_details.cpu_load_1, site_details.cpu_load_5, site_details.cpu_load_15, site_details.memory_total_amount, site_details.memory_usage, site_details.disk_total_size, site_details.disk_usage, site_details.instance_count, site_details.instance_statuses, site_details.member_count, site_details.member_statuses, site_details.joined_at, site_details.updated_at
  FROM site_details
  ORDER BY site_details.core_site_id, site_details.status
`)

var siteDetailObjectsByStatus = cluster.RegisterStmt(`
SELECT site_details.core_site_id, site_details.status, site_details.id, site_details.cpu_total_count, site_details.cpu_load_1, site_details.cpu_load_5, site_details.cpu_load_15, site_details.memory_total_amount, site_details.memory_usage, site_details.disk_total_size, site_details.disk_usage, site_details.instance_count, site_details.instance_statuses, site_details.member_count, site_details.member_statuses, site_details.joined_at, site_details.updated_at
  FROM site_details
  WHERE ( site_details.status = ? )
  ORDER BY site_details.core_site_id, site_details.status
`)

var siteDetailObjectsByCoreSiteID = cluster.RegisterStmt(`
SELECT site_details.core_site_id, site_details.status, site_details.id, site_details.cpu_total_count, site_details.cpu_load_1, site_details.cpu_load_5, site_details.cpu_load_15, site_details.memory_total_amount, site_details.memory_usage, site_details.disk_total_size, site_details.disk_usage, site_details.instance_count, site_details.instance_statuses, site_details.member_count, site_details.member_statuses, site_details.joined_at, site_details.updated_at
  FROM site_details
  WHERE ( site_details.core_site_id = ? )
  ORDER BY site_details.core_site_id, site_details.status
`)

var siteDetailID = cluster.RegisterStmt(`
SELECT site_details.id FROM site_details
  WHERE site_details.core_site_id = ? AND site_details.status = ?
`)

var siteDetailCreate = cluster.RegisterStmt(`
INSERT INTO site_details (core_site_id, status, cpu_total_count, cpu_load_1, cpu_load_5, cpu_load_15, memory_total_amount, memory_usage, disk_total_size, disk_usage, instance_count, instance_statuses, member_count, member_statuses, joined_at, updated_at)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`)

var siteDetailUpdate = cluster.RegisterStmt(`
UPDATE site_details
  SET core_site_id = ?, status = ?, cpu_total_count = ?, cpu_load_1 = ?, cpu_load_5 = ?, cpu_load_15 = ?, memory_total_amount = ?, memory_usage = ?, disk_total_size = ?, disk_usage = ?, instance_count = ?, instance_statuses = ?, member_count = ?, member_statuses = ?, joined_at = ?, updated_at = ?
 WHERE id = ?
`)

// siteDetailColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the SiteDetail entity.
func siteDetailColumns() string {
	return "sites_details.core_site_id, sites_details.status, sites_details.id, sites_details.cpu_total_count, site_details.cpu_load_1, site_details.cpu_load_5, site_details.cpu_load_15, sites_details.memory_total_amount, sites_details.memory_usage, sites_details.disk_total_size, sites_details.disk_usage, sites_details.instance_count, sites_details.instance_statuses, sites_details.member_count, sites_details.member_statuses, sites_details.joined_at, sites_details.updated_at"
}

// getSiteDetails can be used to run handwritten sql.Stmts to return a slice of objects.
func getSiteDetails(ctx context.Context, stmt *sql.Stmt, args ...any) ([]SiteDetail, error) {
	objects := make([]SiteDetail, 0)

	dest := func(scan func(dest ...any) error) error {
		s := SiteDetail{}
		err := scan(&s.CoreSiteID, &s.Status, &s.ID, &s.CPUTotalCount, &s.CPULoad1, &s.CPULoad5, &s.CPULoad15, &s.MemoryTotalAmount, &s.MemoryUsage, &s.DiskTotalSize, &s.DiskUsage, &s.InstanceCount, &s.InstanceStatuses, &s.MemberCount, &s.MemberStatuses, &s.JoinedAt, &s.UpdatedAt)
		if err != nil {
			return err
		}

		objects = append(objects, s)

		return nil
	}

	err := query.SelectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"sites_details\" table: %w", err)
	}

	return objects, nil
}

// getSiteDetailsRaw can be used to run handwritten query strings to return a slice of objects.
func getSiteDetailsRaw(ctx context.Context, tx *sql.Tx, sql string, args ...any) ([]SiteDetail, error) {
	objects := make([]SiteDetail, 0)

	dest := func(scan func(dest ...any) error) error {
		s := SiteDetail{}
		err := scan(&s.CoreSiteID, &s.Status, &s.ID, &s.CPUTotalCount, &s.CPULoad1, &s.CPULoad5, &s.CPULoad15, &s.MemoryTotalAmount, &s.MemoryUsage, &s.DiskTotalSize, &s.DiskUsage, &s.InstanceCount, &s.InstanceStatuses, &s.MemberCount, &s.MemberStatuses, &s.JoinedAt, &s.UpdatedAt)
		if err != nil {
			return err
		}

		objects = append(objects, s)

		return nil
	}

	err := query.Scan(ctx, tx, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"sites_details\" table: %w", err)
	}

	return objects, nil
}

// GetSiteDetails returns all available site_details.
// generator: site_detail GetMany
func GetSiteDetails(ctx context.Context, tx *sql.Tx, filters ...SiteDetailFilter) ([]SiteDetail, error) {
	var err error

	// Result slice.
	objects := make([]SiteDetail, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = cluster.Stmt(tx, siteDetailObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"siteDetailObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.Status != nil && filter.CoreSiteID == nil {
			args = append(args, []any{filter.Status}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, siteDetailObjectsByStatus)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"siteDetailObjectsByStatus\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(siteDetailObjectsByStatus)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"siteDetailObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.CoreSiteID != nil && filter.Status == nil {
			args = append(args, []any{filter.CoreSiteID}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, siteDetailObjectsByCoreSiteID)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"siteDetailObjectsByCoreSiteID\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(siteDetailObjectsByCoreSiteID)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"siteDetailObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Status == nil && filter.CoreSiteID == nil {
			return nil, fmt.Errorf("Cannot filter on empty SiteDetailFilter")
		} else {
			return nil, fmt.Errorf("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getSiteDetails(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getSiteDetailsRaw(ctx, tx, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"sites_details\" table: %w", err)
	}

	return objects, nil
}

// GetSiteDetail returns the site_detail with the given key.
// generator: site_detail GetOne
func GetSiteDetail(ctx context.Context, tx *sql.Tx, coreSiteID int64, status string) (*SiteDetail, error) {
	filter := SiteDetailFilter{}
	filter.CoreSiteID = &coreSiteID
	filter.Status = &status

	objects, err := GetSiteDetails(ctx, tx, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"sites_details\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, api.StatusErrorf(http.StatusNotFound, "SiteDetail not found")
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"sites_details\" entry matches")
	}
}

// GetSiteDetailID return the ID of the site_detail with the given key.
// generator: site_detail ID
func GetSiteDetailID(ctx context.Context, tx *sql.Tx, coreSiteID int64, status string) (int64, error) {
	stmt, err := cluster.Stmt(tx, siteDetailID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"siteDetailID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, coreSiteID, status)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, api.StatusErrorf(http.StatusNotFound, "SiteDetail not found")
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"sites_details\" ID: %w", err)
	}

	return id, nil
}

// SiteDetailExists checks if a site_detail with the given key exists.
// generator: site_detail Exists
func SiteDetailExists(ctx context.Context, tx *sql.Tx, coreSiteID int64, status string) (bool, error) {
	_, err := GetSiteDetailID(ctx, tx, coreSiteID, status)
	if err != nil {
		if api.StatusErrorCheck(err, http.StatusNotFound) {
			return false, nil
		}

		return false, err
	}

	return true, nil
}

// CreateSiteDetail adds a new site_detail to the database.
// generator: site_detail Create
func CreateSiteDetail(ctx context.Context, tx *sql.Tx, object SiteDetail) (int64, error) {
	// Check if a site_detail with the same key exists.
	exists, err := SiteDetailExists(ctx, tx, object.CoreSiteID, object.Status)
	if err != nil {
		return -1, fmt.Errorf("Failed to check for duplicates: %w", err)
	}

	if exists {
		return -1, api.StatusErrorf(http.StatusConflict, "This \"sites_details\" entry already exists")
	}

	args := make([]any, 16)

	// Populate the statement arguments.
	args[0] = object.CoreSiteID
	args[1] = object.Status
	args[2] = object.CPUTotalCount
	args[3] = object.CPULoad1
	args[4] = object.CPULoad5
	args[5] = object.CPULoad15
	args[6] = object.MemoryTotalAmount
	args[7] = object.MemoryUsage
	args[8] = object.DiskTotalSize
	args[9] = object.DiskUsage
	args[10] = object.InstanceCount
	args[11] = object.InstanceStatuses
	args[12] = object.MemberCount
	args[13] = object.MemberStatuses
	args[14] = object.JoinedAt
	args[15] = object.UpdatedAt

	// Prepared statement to use.
	stmt, err := cluster.Stmt(tx, siteDetailCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"siteDetailCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil {
		return -1, fmt.Errorf("Failed to create \"sites_details\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"sites_details\" entry ID: %w", err)
	}

	return id, nil
}

// UpdateSiteDetail updates the site_detail matching the given key parameters.
// generator: site_detail Update
func UpdateSiteDetail(ctx context.Context, tx *sql.Tx, coreSiteID int64, status string, object SiteDetail) error {
	id, err := GetSiteDetailID(ctx, tx, coreSiteID, status)
	if err != nil {
		return err
	}

	stmt, err := cluster.Stmt(tx, siteDetailUpdate)
	if err != nil {
		return fmt.Errorf("Failed to get \"siteDetailUpdate\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(object.CoreSiteID, object.Status, object.CPUTotalCount, object.CPULoad1, object.CPULoad5, object.CPULoad15, object.MemoryTotalAmount, object.MemoryUsage, object.DiskTotalSize, object.DiskUsage, object.InstanceCount, object.InstanceStatuses, object.MemberCount, object.MemberStatuses, object.JoinedAt, object.UpdatedAt, id)
	if err != nil {
		return fmt.Errorf("Update \"sites_details\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}
