# NOTE: no point in setting up patches for this as these configs are most likely going to change
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: 'postgres:17-alpine'
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1000m" # Up to 1 full core
          requests:
            cpu: "1000m" # Use 1 full core
        ports:
        - name: db 
          containerPort: 5432
        envFrom:
        - configMapRef:
            name: config
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        # this is where data is stored inside the container, not host
        - name: db-volume-mount
          mountPath: /var/lib/postgresql/data
          
      volumes:
      - name: db-volume-mount
        persistentVolumeClaim:
          claimName: db-pvc