apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: local
    app: db
spec:
  accessModes:
    - ReadWriteMany
  # NOTE: this should only be used for development purposes
  # since we are using kind for local cluster setup, the data is stored inside the kind node container
  # the data in the kind node container is mapped to host path /data/postgresql in kind-config.yaml
  # for production, persistent volume backed by cloud providers should be used or,
  # shared storage like NFS or Ceph should be used
  hostPath:
    path: /data/postgresql