apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: cluster-manager-dev

manifests:
  kustomize:
    paths:
    - deployment/k8s/dev
  hooks:
    # NOTE: we want to make sure that certificate is created before the deployment
    # therefore we are not deploying the certificate related resources using kustomize
    before:
      - host:
          command: ["deployment/k8s/base/cert/init-cert.sh"]

deploy:
  statusCheck: true
  statusCheckDeadlineSeconds:	180
  tolerateFailuresUntilDeadline: true
  kubectl: {}

profiles:
- name: docker
  build:
    artifacts:
    - image: lxd-cluster-manager
      context: .
      docker:
        dockerfile: deployment/docker/dockerfile.dev
        target: dev
        buildArgs:
          BUILD_REF: "development"
      sync:
        infer:
        - 'cmd/'
        - 'config/'
        - 'internal/'
        - 'go.mod'
        - 'go.sum'
  portForward:
  - resourceType: service
    resourceName: management-api-svc
    port: management-api
    localPort: 9000
  - resourceType: service
    resourceName: cluster-connector-svc
    port: cluster-conn
    localPort: 9001
  # For debugging purposes, we can connect via pgadmin here
  - resourceType: service
    resourceName: db-svc
    port: db
    localPort: 5432

- name: debug
  build:
    artifacts:
    - image: lxd-cluster-manager
      context: .
      docker:
        dockerfile: deployment/docker/dockerfile.dev
        target: debug
        buildArgs:
          BUILD_REF: "development" 
          DEBUG: "true"
  portForward:
  - resourceType: deployment
    resourceName: management-api-depl
    port: management-api
    localPort: 9000
  - resourceType: deployment
    resourceName: cluster-connector-depl
    port: cluster-conn
    localPort: 9001
  - resourceType: deployment
    resourceName: management-api-depl
    port: debug  # Debug port exposed by Delve
    localPort: 40000
  - resourceType: deployment
    resourceName: cluster-connector-depl
    port: debug  # Debug port exposed by Delve
    localPort: 40001
  - resourceType: StatefulSet
    resourceName: db-ss
    port: db
    localPort: 5432

# NOTE: this profile is for testing builds with rocks, use the docker profile for local development
- name: rock
  build:
    artifacts:
    - image: "lxd-cluster-manager"
      sync:
        infer:
        - 'cmd/'
        - 'config/'
        - 'internal/'
        - 'go.mod'
        - 'go.sum'
      custom:
        buildCommand: ./deployment/rock/build.sh
        dependencies:
          paths:
            - rockcraft.yaml
      platforms: ["linux/amd64"]
  portForward:
  - resourceType: service
    resourceName: management-api-svc
    port: management-api
    localPort: 9000
  - resourceType: service
    resourceName: cluster-connector-svc
    port: cluster-conn
    localPort: 9001
  # For debugging purposes, we can connect via pgadmin here
  - resourceType: service
    resourceName: db-svc
    port: db
    localPort: 5432
