apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: cluster-manager-dev
build:
  artifacts:
  - image: cluster-manager-img
    context: .
    docker:
      dockerfile: deployment/docker/dockerfile.dev
      target: dev
      buildArgs:
        BUILD_REF: "development" 
    # trigger rebuild of image when any go files change
    sync:
      infer:
      - '**/*.go'

# default dev deploy
deploy:
  kustomize:
    paths:
    - deployment/k8s/dev
    hooks:
      # NOTE: we want to make sure that certificate is created before the deployment
      # therefore we are not deploying the certificate related resources using kustomize
      before:
        - host:
            command: ["deployment/k8s/base/cert/init-cert.sh"]

portForward:
- resourceType: deployment
  resourceName: management-depl
  port: management
  localPort: 9000
- resourceType: deployment
  resourceName: control-depl
  port: control
  localPort: 9001
# For debugging purposes, we can connect via pgadmin here
- resourceType: deployment
  resourceName: db-depl
  port: db
  localPort: 5432

profiles:
- name: debug
  build:
    artifacts:
    - image: cluster-manager-img
      context: .
      docker:
        dockerfile: deployment/docker/dockerfile.dev
        target: debug
        buildArgs:
          BUILD_REF: "development" 
          DEBUG: "true"
  portForward:
  - resourceType: deployment
    resourceName: management-depl
    port: management
    localPort: 9000
  - resourceType: deployment
    resourceName: control-depl
    port: control
    localPort: 9001
  - resourceType: deployment
    resourceName: management-depl
    port: debug  # Debug port exposed by Delve
    localPort: 40000
  - resourceType: deployment
    resourceName: control-depl
    port: debug  # Debug port exposed by Delve
    localPort: 40001
  - resourceType: deployment
    resourceName: db-depl
    port: db
    localPort: 5432