apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-api-depl
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: management-api
  template:
    metadata:
      labels:
        app: management-api
    spec:
      # NOTE: for local development, have the pods run on the same network as the host
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: management-api
        resources:
          limits:
            cpu: "2000m" # Up to 2 full cores
          requests:
            cpu: "1000m" # Use 1 full cores
        image: cluster-manager-img
        ports:
        - name: debug
          containerPort: 40000