apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-api-depl
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: management-api
  template:
    metadata:
      labels:
        app: management-api
    spec:
      containers:
      - name: management-api
        resources:
          limits:
            cpu: "2000m" # Up to 2 full cores
          requests:
            cpu: "1000m" # Use 1 full cores
        image: lxd-cluster-manager
        ports:
        - name: debug
          containerPort: 40000