apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/config
- ../base/db
- ../base/management-api
- ../base/cluster-connector
- ../base/ingress

patches:
- path: ./config/dev-config.yaml
- path: ./management-api/dev-depl.yaml
- path: ./management-api/dev-svc.yaml
- path: ./cluster-connector/dev-depl.yaml
- path: ./cluster-connector/dev-svc.yaml
