apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: management-api-cert
spec:
  # the secret in which the certificate will be stored, this can be mounted in deployments for application use
  secretName: management-api-cert-secret
  # how long the certificate is valid for
  duration: 2160h # 90 days
  # how long before the certificate's expiration it should be renewed
  renewBefore: 360h # 15 days
  # domains that the certificate will cover
  dnsNames:
    - "localhost"
  # for local development only, we setup the self-signed certificate to function as a CA
  isCA: true
  commonName: dev-ca
  issuerRef:
    name: cert-issuer
    kind: ClusterIssuer