apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    app: config
data:
  # configs for the database deployment
  POSTGRES_DB: base
  POSTGRES_USER: base
  POSTGRES_PASSWORD: base
  # configs for the management-api deployment
  DB_PORT: base
  DB_USER: base
  DB_PASSWORD: base
  DB_NAME: base
  DB_HOST: base
  DB_MAX_OPEN: base
  DB_MAX_IDLE: base
  DB_DISABLE_TLS: base
  SERVER_HOST: base
  MANAGEMENT_API_PORT: base
  CLUSTER_CONNECTOR_PORT: base
  # TODO: define proper versioning strategy
  VERSION: base
  MANAGEMENT_API_TLS_PATH: /etc/ssl/management-api
  CLUSTER_CONNECTOR_TLS_PATH: /etc/ssl/cluster-connector
  CLUSTER_CONNECTOR_ADDRESS: base
  # oidc configs
  OIDC_CLIENT_ID: base
  OIDC_ISSUER: base
  OIDC_AUDIENCE: base