apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-connector-depl
spec:
  selector:
    matchLabels:
      app: cluster-connector
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cluster-connector
    spec:
      containers:
      - name: cluster-connector
        image: localhost:32000/lxd-cluster-manager:1.0.0
        command:
        - /usr/bin/lxd-cluster-manager
        ports:
        - containerPort: 9000
          name: cluster-conn
        readinessProbe:
          httpGet:
            path: /status
            port: 10000
          failureThreshold: 10
          initialDelaySeconds: 1
          periodSeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /status
            port: 10000
          failureThreshold: 10
          initialDelaySeconds: 1
          periodSeconds: 30
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: config
        env:
        - name: SERVICE
          value: cluster-connector
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 200m
        volumeMounts:
        - mountPath: /etc/ssl/management-api
          name: management-api-cert-volume
          readOnly: true
        - mountPath: /etc/ssl/cluster-connector
          name: cluster-connector-cert-volume
          readOnly: true
      volumes:
      - name: management-api-cert-volume
        secret:
          secretName: management-api-cert-secret
      - name: cluster-connector-cert-volume
        secret:
          secretName: cluster-connector-cert-secret
