apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  # configs for the management-api deployment
  DB_PORT: "5432"
  DB_USER: admin
  DB_PASSWORD: admin
  DB_NAME: cm
  DB_HOST: db-svc
  DB_MAX_OPEN: "5"
  DB_MAX_IDLE: "2"
  DB_DISABLE_TLS: "true"
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "9000"
  # TODO: define proper versioning strategy
  VERSION: "development"
  CLUSTER_CONNECTOR_DOMAIN: "cc.lxd-cm.local"
  CLUSTER_CONNECTOR_PORT: "30000"
  # oidc configs
  OIDC_CLIENT_ID: RYDnMpkygLAMfeo17lU7LYwWGxisRuRR
  OIDC_CLIENT_SECRET: CNKX4UmrZKZJq5rJy5VM_JfcNPqkws1rwWWQk_q0oyZ8gABARr19ic7xrhPssGA1
  OIDC_ISSUER: https://dev-h6c02msuggpi6ijh.eu.auth0.com/
  OIDC_AUDIENCE: https://dev-h6c02msuggpi6ijh.eu.auth0.com/api/v2/
  PROMETHEUS_BASE_URL: http://192.168.1.133/cos-prometheus-0/api/v1/write
  GRAFANA_BASE_URL: http://192.168.1.133:30001/cos-grafana/d/bGY-LSB7k
