# TODO: split this into separate configmaps
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    app: db
data:
  # configs for the database deployment
  POSTGRES_DB: cm
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  # configs for the management-api deployment
  DB_PORT: "5432"
  DB_USER: admin
  DB_PASSWORD: admin
  DB_NAME: cm
  DB_HOST: localhost
  DB_MAX_OPEN: "5"
  DB_MAX_IDLE: "2"
  DB_DISABLE_TLS: "true"
  SERVER_HOST: "localhost"
  MANAGEMENT_API_PORT: "9000"
  CLUSTER_CONNECTOR_PORT: "9001"
  TEST_MODE: "false"
  # TODO: define proper versioning strategy
  VERSION: "development"
  CLUSTER_CONNECTOR_ADDRESS: "localhost:9001"
  # oidc configs
  OIDC_CLIENT_ID: NBXrnTZUrulBYNPuc4raZySTEWDTuvM2
  OIDC_ISSUER: https://dev-xjrvvfikbsv4jxn7.us.auth0.com/
  OIDC_AUDIENCE: https://dev-xjrvvfikbsv4jxn7.us.auth0.com/api/v2/