apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  # configs for the management-api deployment
  DB_PORT: "5432"
  DB_USER: admin
  DB_PASSWORD: admin
  DB_NAME: cm
  DB_HOST: db-svc
  DB_MAX_OPEN: "5"
  DB_MAX_IDLE: "2"
  DB_DISABLE_TLS: "true"
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "9000"
  TEST_MODE: "false"
  # TODO: define proper versioning strategy
  VERSION: "development"
  CLUSTER_CONNECTOR_ADDRESS: "cc.lxd-cm.local:30000"
  # oidc configs
  OIDC_CLIENT_ID: OZSAeCbqAXZid3LL1gRQEkLXP9KlwZtJ
  OIDC_ISSUER: https://lxd-ui-demo.us.auth0.com/
  OIDC_AUDIENCE: https://lxd-ui-demo.us.auth0.com/api/v2/
  PROMETHEUS_BASE_URL: http://192.168.1.133/cos-prometheus-0/api/v1/write
  GRAFANA_BASE_URL: http://192.168.1.133:30001/cos-grafana/d/bGY-LSB7k
