name: lxd-cluster-manager
version: 0.1.0
icon: snap/gui/logo.svg
base: core22
summary: LXD Cluster Manager, an overview of multiple LXD installations
description: LXD Cluster Manager presents an overview of resource usage and availability for all connected LXD clusters or LXD single node installations. In the future it will allow shifting workloads between clusters.
confinement: strict

apps:
  # Service
  daemon:
    command: local/daemon.start
    daemon: simple
    plugs:
      - lxd
      - network
      - network-bind

  # Commands
  lxd-cluster-manager:
    command: local/lxd-cluster-manager
    plugs:
      - network

parts:
  dqlite:
    source: https://github.com/canonical/dqlite
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
      - --enable-build-raft
    stage-packages:
      - liblz4-1
      - libuv1t64
      - sqlite3
    build-packages:
      - liblz4-dev
      - pkg-config
      - libsqlite3-dev
      - libuv1-dev
    organize:
      usr/bin/: bin/
      usr/lib/: lib/
    prime:
      - bin/sqlite3
      - lib/libdqlite*so*
      - lib/*/libsqlite3*so*
      - lib/*/libuv*
      #- lib/*/liblz4.so*  # use liblz4.so from the base snap

  lxd-cluster-manager:
    source: .
    after:
      - dqlite
    build-snaps:
      - go
    plugin: nil
    override-pull: |
      craftctl default
      set -ex

      # Download the dependencies
      go get -d -v -tags=agent ./...
      
      # Setup yarn
      snap install node --channel=20/stable --classic
      npm install yarn --global
    override-build: |
      set -ex

      # Setup build environment
      export CGO_CFLAGS="-I${CRAFT_STAGE}/include/ -I${CRAFT_STAGE}/usr/local/include/"
      export CGO_LDFLAGS="-L${CRAFT_STAGE}/lib/ -L${CRAFT_STAGE}/usr/local/lib/"
      export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"

      # Build the ui
      cd ui && yarn install && yarn build && cd ..
      rm -rf internal/api/static &> /dev/null
      cd internal/api && go generate && cd .. && cd ..

      # Build the binaries
      go build -trimpath -o "${CRAFT_PART_INSTALL}/bin/lxd-cluster-mgr" ./cmd/lxd-cluster-mgr
      go build -trimpath -o "${CRAFT_PART_INSTALL}/bin/lxd-cluster-mgrd" ./cmd/lxd-cluster-mgrd
    prime:
      - bin/lxd-cluster-mgr
      - bin/lxd-cluster-mgrd

  strip:
    after:
      - dqlite
      - lxd-cluster-manager
    plugin: nil
    override-prime: |
      set -x

      # Strip binaries
      find "${CRAFT_PRIME}"/bin -type f -exec strip -s {} +

      # Strip libraries
      find "${CRAFT_PRIME}"/lib -type f -exec strip -s {} +

  wrappers:
    plugin: dump
    source: snap/
