apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-depl
spec:
  selector:
    matchLabels:
      app: management
  template:
    metadata:
      labels:
        app: management
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      initContainers:
      - name: init
        image: cluster-manager-img
        envFrom:
        - configMapRef:
            name: config
        env:
        - name: SERVICE
          value: "admin"
      # TODO: use init containers to do db migration and seeding
      containers:
      - name: management
        image: cluster-manager-img
        ports:
        - name: management
          containerPort: 9000
        # TODO: more ports for readiness and liveness probes
        envFrom:
        - configMapRef:
            name: config
        env:
        - name: SERVICE
          value: "management"
        # mount a volume inside the container, at the path specified
        # this volume will contain the certificate generated by cert-manager for the management service
        volumeMounts:
        - name: management-cert-volume
          mountPath: "/etc/ssl/management"
          readOnly: true
        - name: control-cert-volume
          mountPath: "/etc/ssl/control"
          readOnly: true
      volumes:
      - name: management-cert-volume
        # the certificate is stored in a cluster secret, which will be mounted as a volume in the container
        # the actual .crt and .key file paths are specified in the configmap so that pods may access them by using the environment vars
        secret:
          secretName: management-cert-secret
      - name: control-cert-volume
        secret:
          secretName: control-cert-secret