#! /usr/bin/env bash

set -e

HAPROXY_BIND="$1"
cp haproxy.cfg haproxy-local.cfg
sed -i "s#BIND_ADDRESS#$HAPROXY_BIND#" haproxy-local.cfg
sed -i "s#CLUSTER_MANAGER_BACKEND_IP#$CLUSTER_MANAGER_BACKEND_IP#" haproxy-local.cfg

# generate certificates for dev environment
if [ ! -d "keys" ]; then
    mkdir -p keys
    openssl req -nodes -x509 -newkey ec -pkeyopt ec_paramgen_curve:secp384r1 -sha384 -keyout keys/lxd-cm.key -out keys/lxd-cm.crt -subj "/C=GB/ST=London/L=London/O=LXD UI/OU=dev/CN=localhost" -days 3000
    cat keys/lxd-cm.key keys/lxd-cm.crt > keys/lxd-cm.pem
    cp keys/lxd-cm.key keys/lxd-cm.crt.key
    echo 'finished generating certificates'
fi

haproxy -f haproxy-local.cfg

echo "Listening at https://$HAPROXY_BIND"

vite --host 2>&1 | grep -v :3000

