#! /usr/bin/env bash

set -e

HAPROXY_BIND="$1"
cp haproxy.cfg haproxy-local.cfg
sed -i "s#BIND_ADDRESS#$HAPROXY_BIND#" haproxy-local.cfg
sed -i "s#CLUSTER_MANAGER_BACKEND_IP#$CLUSTER_MANAGER_BACKEND_IP#" haproxy-local.cfg

# generate certificates for dev environment
if [ ! -d "keys" ]; then
    mkdir -p keys
    openssl req -nodes -x509 -newkey rsa:2048 -keyout keys/lxd-sm.key -out keys/lxd-sm.crt -subj "/C=GB/ST=London/L=London/O=LXD SM/OU=dev/CN=localhost" -days 3000
    openssl dhparam -out keys/dhparams.pem 2048
    cat keys/lxd-sm.key keys/lxd-sm.crt > keys/lxd-sm.pem
    cp keys/lxd-sm.key keys/lxd-sm.crt.key
    echo 'finished generating certificates'
fi

haproxy -f haproxy-local.cfg

echo "Listening at https://$HAPROXY_BIND"

vite --host 2>&1 | grep -v :3000

