name: PR checks
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commits:
    permissions:
      pull-requests: read   # to get list of commits from the PR
    name: Canonical CLA signed and Signed-off-by (DCO)
    runs-on: ubuntu-latest
    steps:
    - name: Check if CLA signed
      uses: canonical/has-signed-canonical-cla@v1
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check that all commits are signed-off
      uses: tim-actions/dco@master
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}

  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Install dependencies
        run: |
          set -eux
          sudo add-apt-repository ppa:dqlite/dev -y --no-update
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libdqlite-dev
          cd ui && yarn install --immutable

      - name: Build LXD Cluster Manager
        run: make

      - name: Run static analysis
        run: |
          set -eux
          make test-static

      - name: Run backend e2e tests
        run: |
          set -eux
          make test-e2e

  ui-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd ui && yarn install --immutable

      - name: Lint scss
        run: cd ui && yarn lint-scss

      - name: Lint JS
        run: cd ui && yarn lint-js

  ui-e2e-tests:
    environment: ci-end-to-end
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: ["chromium", "firefox"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Install Dotrun
        run: |
          sudo pip3 install dotrun requests==2.31.0 # requests version is pinned to avoid breaking changes, can be removed once issue is resolved: https://github.com/docker/docker-py/issues/3256

      - name: Install backend dependencies
        run: |
          set -eux
          sudo add-apt-repository ppa:dqlite/dev -y --no-update
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libdqlite-dev

      - name: Install UI dependencies
        run: |
          set -eux
          cd ui && yarn install --immutable
      
      - name: Make LXD Cluster Manager Binaries
        run: make compile

      - name: Run Cluster Manager daemon
        run: lxd-cluster-mgrd --state-dir ./state/dir1/ &

      - name: Initialise Cluster Manager
        run: |
          lxd-cluster-mgr --state-dir ./state/dir1/ waitready
          lxd-cluster-mgr --state-dir ./state/dir1/ init "member1" 0.0.0.0:9001 --bootstrap --control-address 0.0.0.0:9010

      - name: Add dummy data to Cluster Manager
        run: |
          set -eux
          sudo chmod 0777 ../lxd-cluster-manager
          scripts/generate_clusters.sh

      - name: Install Playwright Browsers
        run: cd ui && npx playwright install --with-deps ${{ matrix.browser }}

      - name: Setup for tests
        shell: bash
        env:
          OIDC_USER: ${{ secrets.OIDC_USER }}
          OIDC_PASSWORD: ${{ secrets.OIDC_PASSWORD }}
          OIDC_ISSUER: ${{ secrets.OIDC_ISSUER }}
          OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
          OIDC_AUDIENCE: ${{ secrets.OIDC_AUDIENCE }}
        run: |
          echo "OIDC_USER=$OIDC_USER" >> ui/.env.local
          echo "OIDC_PASSWORD=$OIDC_PASSWORD" >> ui/.env.local
          echo "OIDC_ISSUER=$OIDC_ISSUER" >> ui/.env.local
          echo "OIDC_CLIENT_ID=$OIDC_CLIENT_ID" >> ui/.env.local
          echo "OIDC_AUDIENCE=$OIDC_AUDIENCE" >> ui/.env.local
          scripts/generate_configs.sh

      - name: Run Playwright tests
        run: cd ui && npx playwright test --project ${{ matrix.browser }}

      - name: Upload ${{ matrix.browser }} blob reports to be merged
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.browser }}
          path: ui/blob-report
          retention-days: 1

  merge-ui-e2e-reports: 
    if: always()
    needs: [ui-e2e-tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v4
      with:
        path: blob-reports
        pattern: blob-report-*
        merge-multiple: true
    
    # NOTE: there is no need to install playwright dependencies since we only need to merge reports here
    - name: Merge into HTML Report
      run: npx playwright merge-reports --reporter html ./blob-reports
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 14
