name: PR checks
on: pull_request

jobs:

  commits:
    permissions:
      pull-requests: read   # to get list of commits from the PR
    name: Canonical CLA signed and Signed-off-by (DCO)
    runs-on: ubuntu-latest
    steps:
    - name: Check if CLA signed
      uses: canonical/has-signed-canonical-cla@v1
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check that all commits are signed-off
      uses: tim-actions/dco@master
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}

  ui-lint-scss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd ui && yarn install --immutable

      - name: Lint scss
        run: cd ui && yarn lint-scss

  ui-lint-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install node dependencies
        run: cd ui && yarn install --immutable

      - name: Lint JS
        run: cd ui && yarn lint-js
